version: '3.7'

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: eim11_app
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app/
    networks:
      - app-network
    

networks:
  app-network:
    driver: bridge    
